# workdir
# /home/runner/work/FireLamp_JeeUI/FireLamp_JeeUI


name: GitHub release creator pipeline

on:
  workflow_dispatch:      # Manual start
  push:
    branches: [ testing ]
    tags:
      - "t*.*.*"

jobs:
  PublishRelease:
    runs-on: ubuntu-latest
    if: github.repository == 'vortigont/FireLamp_JeeUI'
    continue-on-error: false
    steps:
      - name: Collect build images
        id: prepare_descr
        shell: bash
        run: |
          mkdir ~/artifacts
          pwd
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo "testing..." > ${{ github.workspace }}-CHANGELOG.txt
          ls ${{ github.workspace }}-CHANGELOG.txt
          touch ~/artifacts/${{ github.ref_name }}.txt
          ls ~/artifacts/${{ github.ref_name }}.txt
          github.ref_name
          find ~/ -name 'factory.*.bin'
          find ~/ -name 'firmware.*.bin'
          find .pio/build/ -name "factory.*.bin" -exec mv -t ~/artifacts/ {} +
          find .pio/build/ -name "firmware.*.bin" -exec mv -t ~/artifacts/ {} +
